site_name: Sciences numériques et technologie
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: my_theme
      toggle:
        icon: material/weather-night
        name: Passer en mode nuit
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Passer en mode jour
  font:
    text: Roboto
    code: Roboto Mono

site_url: https://snt.erwandemerville.fr/
copyright: Copyright &copy; 2023 - Erwan Demerville
nav:
  - Accueil:
    - index.md
  - Rentrée 2025:
    - accueil/index.md
    - Énigme localisation: accueil/enigme_localisation.md
  - Introduction à l'informatique:
    - intro_info/index.md
    - Numération binaire: intro_info/numeration_binaire.md
    - Codage ASCII: intro_info/ascii.md
  - Les réseaux sociaux:
    - reseaux_sociaux/index.md
    - Introduction aux réseaux sociaux: reseaux_sociaux/introduction.md
    - Activité - Stratégie des réseaux: reseaux_sociaux/dopamine.md
    - Activité - Modéliser un réseau: reseaux_sociaux/modelisation.md
    - Activité - Modèle économique des réseaux: reseaux_sociaux/modele_economique.md
    - Activité - Vie privée et cyberharcèlement: reseaux_sociaux/cyberharcelement.md
    - Cours: reseaux_sociaux/cours.md
  - Le web:
    - web/index.md
    - Activités et projet:
      - Activité - Le web et son histoire: web/histoire.md
      - Activités - HTML et CSS: web/decouverte_web.md
      - Activité - Sécurité et vie privée: web/securite.md
      - Activité - Moteurs de recherche: web/moteurs_recherche.md
      - Projet - Un site web: web/projet_site_web.md
      - Sites web d'élèves: web/sites_eleves.md
    - Cours:
      - Cours - HTML et CSS: web/cours_html_css.md
  - Données structurées:
    - donnees_structurees/index.md
    - Cours: donnees_structurees/cours.md
    - TP Python: donnees_structurees/tp_tables.md
    - TD - Données structurées: https://opale-donnees.erwandemerville.fr/
    - TP - Tableur Excel: donnees_structurees/tp_tableur.md
  - Localisation, cartographie et mobilité:
    - localisation/index.md
    - Cours: localisation/cours.md
    - Activité - Plateformes carto.: localisation/src/activite3_plateformes.pdf
    - Activité - Trame NMEA: localisation/src/activite4_NMEA.pdf
    - Convertisseur GPS: localisation/convertgps.md
  - Photographie:
    - photographie/index.md
  - Initiation Python:
    - initiation_python/index.md
    - Py-rates: https://py-rates.org/
    - Documents: initiation_python/documents.md
    - Notebooks: initiation_python/notebooks.md
  - Codecombat: https://codecombat.com/students?_cc=ShelfMouthMap
  - Rendu des travaux: rendus.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: Sur cette page
      permalink: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.progressbar
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: False
  - open-in-new-tab
  - macros

extra_css:
  - stylesheets/extra.css
  - stylesheets/progressbar.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

